### ISSUE TITLE
Doesn't behave as expected

### ISSUE THREAD

**Issue by Zayelion** [adrianojn/checkdb#1]
For the first run through I was expecting a comparison of a generated database based on the SQL files in the directory. It counted the files, output that then declared only 1 missing card instead of the actual number of missing cards.

I'm just guessing but I think something is going wrong in the setup of the for loop around line 117.

**Comment by adrianojn** [comment]
With the loop inverted it reports `3373 missing cards`. Is this the expected?

**Comment by Zayelion** [comment]
Yes `3373` cards missing was the expected results, with those ID numbers outputted to the error log. (id names **pairs** would technically be more useful)

**Comment by adrianojn** [comment]
current format is:

```
27551 Limit Reverse
32864 The 13th Grave
41777 Gem-Enhancement
50755 Magician's Circle
62121 Castle of Dark Illusions
102380 Lava Golem
114932 Seismic Crasher
123709 Laval Lancelord
```

any changes needed?

**Comment by Zayelion** [comment]
nope that is perfect. Now to wrangle the staff and community.
